// next
import type { Metadata } from 'next';

// styling
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

// others
import Navbar from '@/components/navbar';
import NavHeader from '@/components/navheader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          type='text/css'
          href='https://unpkg.com/@phosphor-icons/web@2.1.1/src/regular/style.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='https://unpkg.com/@phosphor-icons/web@2.1.1/src/fill/style.css'
        />
      </head>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased flex flex-row',
          fontSans.variable,
        )}
      >
        <Navbar />
        <div className='w-full'>
          <NavHeader />
          <main className='w-full'>{children}</main>
        </div>
      </body>
    </html>
  );
}
