// next
import type { Metadata } from 'next';

import NextAuthProvider from '@/app/context/NextAuthProvider';
// styling
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

// others
import Navbar from '@/components/navbar';
import NavHeader from '@/components/navheader';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='stylesheet'
          type='text/css'
          href='https://unpkg.com/@phosphor-icons/web@2.1.1/src/regular/style.css'
        />
        <link
          rel='stylesheet'
          type='text/css'
          href='https://unpkg.com/@phosphor-icons/web@2.1.1/src/fill/style.css'
        />
      </head>
      <body
        className={cn('bg-background font-sans antialiased', fontSans.variable)}
      >
        <NextAuthProvider>
          <div className='min-h-screen flex flex-row'>
            <Navbar />
            <div className='w-full flex flex-col'>
              <NavHeader />
              <main className='grow w-full overflow-x-auto overflow-y-scroll max-h-[calc(100vh-61px)]'>
                {children}
              </main>
            </div>
          </div>
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
