// mypages.js
// 2023-03-01: by jcr

exports.genMainPage = function(lista, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
            </header>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`

    for(let i=0; i < lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7777/pessoas/${lista[i].id}">
                                ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
    }

    pagHTML += `
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}

exports.genPessoaPage = function(pessoa, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>${pessoa.nome}</h1>
            </header>
    
        <div class="w3-container">
            `
    pagHTML += `
            
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}